### ISSUE TITLE
what are the meaning of "i" and "q" in the option --filter_b pw=[i,q] ? 

### ISSUE THREAD

**Issue by yiyian-Lee** [tkchafin/mrbait#12]
hi, 
I need to use vsearch delete duplicate baits.
so I assume that I should use -f pw
but, I can't understand meaning of i and q...
and how pairwise alignment work here

for example, I create a fasta file like so:
>\>test
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

there are 540 A and 30 T, finally are 90 A.

used command:
mrbait -A fasta -b 120

get 10 baits
8 baits are 120 A. like AAAA
1 bait is 60 A, 30 T, 30A. like: AATA
1 bait is 30 T, 90 A, like TAAA

next , I try to use -f pw:

mrbait -A fasta -b 120 -f pw=0.5,0.5
get 1 120 A

mrbait -A fasta -b 120 -f pw=0.5,0.751
get all 3 type of baits, change i can't change result.

so I assume that if q percent of sequences are same, they will treat as same sequences.

mrbait -A fasta -b 120 -f pw=0.751,0.1
but even q is 0.1, when i more than 0.75, I get 2 type of baits.

but, why?

I can't understand how they work, please help me.

p.s., although it is not my problem, but maybe you want to know that: -F pw and -F gc are not work, mrbait say they are invalid option.

thankful,  yi-yan

**Comment by tkchafin** [comment]
Hi Yi-yan, 

The -F pw/gc bug was fixed a while back- seems to be working for me (v1.1.7). Can you update mrbait using:

conda install mrbait -c tylerkchafin -c bioconda -c conda-forge

If the issue persists, please let me know.

**Comment by tkchafin** [comment]
As for the parameters provided for the pw and rc options: These are given as "x,y" where x=identity, defined as (matching columns) / (alignment length - terminal gaps), and y=query coverage defined as (matches + mismatches) / query sequence length. These values are fed directly to a program used for pairwise global alignment (VSEARCH) as the --id and --query_cov arguments. 

As for the reason you are getting unexpected results... I suspect this is because VSEARCH by default masks low complexity sequences. 

You might try again with a more complex test sequence, and then see if the pw filtering gives the expected results? Alternatively, if desirable, I can add an option to turn off dust-masking in VSEARCH.

**Comment by tkchafin** [comment]
Correction: To force reinstall, you need to use: 
conda install mrbait -c tylerkchafin -c bioconda -c conda-forge --force-reinstall

**Comment by tkchafin** [comment]
Update: I've added a --vsearch_qmask flag for v1.2.0 so you can control the masking behavior used with rc and pw filters

**Comment by yiyian-Lee** [comment]
THANK you！
I already downloaded mrbait again
and I know how to use this option.

thank you for your help ~yiyan
