### ISSUE TITLE
mrbait can't work on lower-case sequences fasta 

### ISSUE THREAD

**Issue by yiyian-Lee** [tkchafin/mrbait#15]
hello~
I find this problem.
when I input a fasta file like:
> \>sequence_name
aaaatcgggatttcgtagg

and mrbait say that :
>Program killed: No loci passed filtering.

and stop working.
after I change all characters into upper-case, it work.

but I worry about that some file fuse lower and upper case in one file, can mrbait  work on them?

this problem is easy to resolve, maybe just add this condition into document?

have a nice day!
~yiyan

**Comment by tkchafin** [comment]
Hi Yi-yan, 
Since lower-case bases are often used to indicate soft-masking (e.g. flagged as low-complexity or repetitive), mrbait by default can filter loci/ candidate targets based on the proportion of bases that are masked. 

You can change this behavior for example by altering the filter:
-K,--max_mask	: Maximum proportion of masked bases allowed in a consensus sequence [0.5]

Or in the case of providing alignments, you can set how many individual sequences in the alignment are masked in order to mask the consensus:
-k,--mask	: Threshold proportion for masking (lower case) to include in consensus [0.1]


You can also ask mrbait to find low-complexity regions and mask them for you:
	--dustMask	: Use VSEARCH to mask consensus sequences using the DUST algorithm

**Comment by yiyian-Lee** [comment]
sorry I don't know about masking.
my file full of lower-case bases, I don't know  why
now I know that I have other problem...
thank you  for your help!
