### ISSUE TITLE
mrbait work on only one fasta file input

### ISSUE THREAD

**Issue by yiyian-Lee** [tkchafin/mrbait#7]
hello,
here I some problem for my output......please give me some help.
I use only one fasta file input mrbait.
this fasta file have a lot of sequences, and size of any sequence is about 450 characters.

and using command like so :
    mrbait -T 4 -o mrbait_seq -A fasta_name -b 120 -s tile=60
mrbait finished the work, and gave me output.
then I found that the "out.bait" file is more bigger than the input fasta file.
so I get baits more than input, it's not good.

So, this result is correct? or I have some fault let me can't get right output?
please let me know.

finally, I'm sorry for my bad English.

thankful,
                                      Yi-yian

**Comment by tkchafin** [comment]
Hi Yi-yian, Based on the command you used, MrBait will design baits of length 120 which overlap by 60 bases. So, for all of your input sequences of length 450 you would expect around 6 baits each. So, the output file would have around 6x more lines. Is this not what you had intended? If you can, please tell me exactly what you want the desired output to be  and I'll help you build a command line call to accomplish it.Thanks,Tyler
-------- Original message --------From: yiyian-Lee <notifications@github.com> Date: 7/3/19  7:35 AM  (GMT-06:00) To: tkchafin/mrbait <mrbait@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [tkchafin/mrbait] mrbait work on only one fasta file input (#7) hello,
here I some problem for my output......please give me some help.
I use only one fasta file input mrbait.
this fasta file have a lot of sequences, and size of any sequence is about 450 characters.
and using command like so :
mrbait -T 4 -o mrbait_seq -A fasta_name -b 120 -s tile=60
mrbait finished the work, and gave me output.
then I found that the "out.bait" file is more bigger than the input fasta file.
so I get baits more than input, it's not good.
So, this result is correct? or I have some fault let me can't get right output?
please let me know.
finally, I'm sorry for my bad English.
thankful,
Yi-yian

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tkchafin/mrbait/issues/7?email_source=notifications\u0026email_token=ACTCV65BO4BF7SDVLRZG3ETP5SMJLA5CNFSM4H5FK6OKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G5D5O6A",
"url": "https://github.com/tkchafin/mrbait/issues/7?email_source=notifications\u0026email_token=ACTCV65BO4BF7SDVLRZG3ETP5SMJLA5CNFSM4H5FK6OKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G5D5O6A",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yiyian-Lee** [comment]
Thank you for your help!
maybe I just misunderstand function of mrbait.

before, I assumed that mrbait work like:
     load files -> find consensus region -> find conserved sequences -> find targets -> design bait -> filter...
I hope that I can get conserved sequence from one fasta.
but, there is not finding conserved sequences phase, right?
so, maybe this is incorrect hope...

I only get 2 times bigger output files, I guess that because I am not use --mult_reg flag.

if I want to get some conserved sequences, should I need to use some aligned sequences?

thank for your quick reply and sorry that I'm slow...
have a nice day,
                                        Yi-yian

**Comment by tkchafin** [comment]
Hi Yi-yian, 

You're correct about the workflow of mrbait. I misunderstood what you are trying to do. There is indeed a step which seeks out conserved regions for which baits can ultimately be developed, but you need to provide the program more information on how sequences align to one another.

By default, mrbait considers a FASTA (input with -A) file to be in the form of contigs of a genome, or individual loci, scaffolds, etc- not an alignment. The intended use is that the user would then provide variant information via a VCF file.

In your case, you'll need to input some sort of alignment. Mrbait currently can read these either as XMFA (http://darlinglab.org/mauve/user-guide/files.html) or MAF (https://genome.ucsc.edu/FAQ/FAQformat.html#format5) formats. Are all sequences in your file representing a single locus? 

If so, it will be very easy to create an XMFA from it. Let me know if you need additional help with formatting your input file. 

Tyler

**Comment by yiyian-Lee** [comment]
Hello!
ok, so the FASTA format input only work for change all sequences to baits, right?
I will aligned genomes and use mrbait again, 
thank you for your advice! 

good luck,
                    yi-yian

**Comment by tkchafin** [comment]
You are correct. You'll either need the multi-fasta or MAF format, or to generate a variant table (VCF). Going to close this issue. Don't hesitate to contact me if you hit any other snags w/ mrbait
